#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



#-------------------------------------------------------------------------------------
git add plugin/Flashcard.vim
git add pushit
git add README.md
git commit -m "Update"
git push -u origin main
REPO=vim-Flashcard
rm -rf $HOME/.vim/bundle/$REPO
vim  -c ":PluginInstall! $REPO" -c ":qa!"
#-------------------------------------------------------------------------------------

